# Topic 01 · NumPy Foundations

A compact hands-on notebook covering arrays, indexing, broadcasting, aggregation, boolean masks and vectorization.

In [ ]:
import numpy as np
np.__version__

## 1. Arrays and shapes
NumPy arrays store homogeneous data and expose shape, dimensionality and dtype.

In [ ]:
x = np.array([2, 4, 6, 8, 10])
A = np.arange(1, 13).reshape(3, 4)
print('x:', x)
print('A:\n', A)
print('shape:', A.shape, 'ndim:', A.ndim, 'dtype:', A.dtype)

x: [ 2  4  6  8 10]
A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
shape: (3, 4) ndim: 2 dtype: int64


## 2. Indexing and slicing
Slices create views in many cases, so mutations can affect the original array.

In [ ]:
print(A[0])
print(A[:, 1])
print(A[1:, 2:])

[1 2 3 4]
[ 2  6 10]
[[ 7  8]
 [11 12]]


## 3. Boolean masks

In [ ]:
mask = A % 2 == 0
print(mask)
print(A[mask])

[[False  True False  True]
 [False  True False  True]
 [False  True False  True]]
[ 2  4  6  8 10 12]


## 4. Broadcasting
Broadcasting lets NumPy combine compatible shapes without explicit Python loops.

In [ ]:
row_offsets = np.array([100, 200, 300, 400])
print(A + row_offsets)

[[101 202 303 404]
 [105 206 307 408]
 [109 210 311 412]]


## 5. Aggregations and axis

In [ ]:
print('sum:', A.sum())
print('column means:', A.mean(axis=0))
print('row max:', A.max(axis=1))

sum: 78
column means: [5. 6. 7. 8.]
row max: [ 4  8 12]


## 6. Vectorization
The vectorized expression is shorter, clearer and usually much faster than a Python loop.

In [ ]:
values = np.arange(1, 11)
result = values ** 2 + 3 * values - 1
print(result)

[  3   9  17  27  39  53  69  87 107 129]


## 7. Practical mini-task
Normalize values to z-scores: subtract the mean and divide by standard deviation.

In [ ]:
scores = np.array([62, 71, 73, 75, 80, 84, 91], dtype=float)
z = (scores - scores.mean()) / scores.std()
print(np.round(z, 3))

[-1.669 -0.638 -0.409 -0.18   0.393  0.851  1.652]


## Takeaways
- `shape`, `dtype`, `ndim` are the first structural checks.
- Boolean masks are the basis of vectorized filtering.
- `axis=0` aggregates down rows (per column); `axis=1` across columns (per row).
- Broadcasting replaces many explicit loops.
- NumPy is the numerical foundation underneath much of Pandas and scikit-learn.